version: '3'

services:
  app:
    image: node:12-alpine
    command: npm run start:dev
    working_dir: /usr/local/server/
    restart: on-failure
    container_name: financial_node
    environment:
      PORT: 3000
    volumes:
      - './:/usr/local/server/'
    ports:
      - '8000:3000'
